mqtt:
  broker_host: 192.168.8.234      
  broker_port: 1883
  keepalive:   30                 # seconds
  reconnect:
    min_delay: 2
    max_delay: 30

vitals:                # Jetson helpers only
  injection_probability: 0.10
  ttl_seconds:          5
